### ISSUE TITLE
Rename to bs-elm for consistency?

### ISSUE THREAD

**Issue by splodingsocks** [jaredramirez/bs-elm#3]
As I'm looking around the community it seems like the current convention for Reason and BS packages alike is to name them `bs-****`. Do you think it'd be good to do the same?

**Comment by jaredramirez** [comment]
I'm not opposed renaming, I originally chose `reason-elm` because I had used `reason-react` prior to writing this.

This should also include changing the exported module to `BsElm` or `Elm`. Of the two, I think I prefer the latter. I'll get to this today.

**Comment by jaredramirez** [comment]
This is done!

**Comment by splodingsocks** [comment]
Wow, so fast! 👏
