### ISSUE TITLE
Rename port types?

### ISSUE THREAD

**Issue by splodingsocks** [jaredramirez/bs-elm#4]
I find it's confusing to remember between `elmOutPort` and `elmInPort` which is which. When I'm writing the code I have to check myself to try and remember whether `elmIn` means "from Elm into Reason" or "from Reason into Elm". 

Do you think it might be more clear to name them:

`portToElm` and `portFromElm`?

**Comment by jaredramirez** [comment]
Thank you for your feedback, I definitely think that those names are more clear! I will update these types.

**Comment by jaredramirez** [comment]
This is done in https://github.com/jaredramirez/bs-elm/releases/tag/v1.0.0

**Comment by splodingsocks** [comment]
Awesome! 👏 👏👏👏👏
Thanks!
